name: dnb
description: A platform-agnostic Dart client library for interacting with DNB's Open Banking APIs.
version: 1.3.0+1
homepage: https://github.com/arnemolland/dart-dnb

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  http: ^0.12.1
  equatable: ^1.2.0
  json_annotation: ^3.0.1
  uuid: ^2.0.4

dev_dependencies:
  test: ^1.14.7
  pedantic: ^1.9.0
  dotenv: ^2.0.0
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  puppeteer: ^1.17.0
