name: dnb
description: A platform-agnostic Dart client library for interacting with DNB's Open Banking APIs.
version: 1.2.0+1
author: Arne Molland <arnolaim@gmail.com>
homepage: https://github.com/arnemolland/dart-dnb

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  http: ^0.12.0+2
  sigv4: ^2.1.0

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.8.0+1
