name: dnb
description: A platform-agnostic Dart client library for interacting with DNB's open APIs.
version: 1.1.0
author: Arne Molland <arnolaim@gmail.com>
homepage: https://github.com/arnemolland/dart-dnb

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  meta: ^1.1.7
  http: ^0.12.0
  sigv4: ^1.0.0

dev_dependencies:
  test: ^1.6.4
  dotenv: ^1.0.0