name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Decode certificate/key
        run: ./certs.sh
        env:
          PSD2_PRIVATE_KEY: ${{ secrets.PSD2_PRIVATE_KEY }}
          PSD2_CERTIFICATE: ${{ secrets.PSD2_CERTIFICATE }}
      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: pub run test
